### ISSUE TITLE
Delivery Methods

### ISSUE THREAD

**Issue by gadgetto** [modmore/docs#16]
On page [Delivery Methods](https://github.com/modmore/docs/blob/master/en/05_SimpleCart/v2.x/02_Manager/05_Administration/02_Delivery_Methods.md) there is an issue with:

- Price: The price that should be calculated for this methodLanguageSelect the language of the Title and Descriptions. Note: only SimpleCart languages available here

Should be:

- Price: The price that should be calculated for this method
- Language: Select the language of the Title and Descriptions. Note: only SimpleCart languages available here

**Comment by Mark-H** [comment]
Thanks Martin! Fixed :)
