### ISSUE TITLE
Bundels can;t hold digital products

### ISSUE THREAD

**Issue by hurby** [modmore/docs#243]
Placing one or more digitalproducts in a productbundel doesn't work.
Download links are not showing in mail and pdf.
Setting the bundel to digitalproduct doesn't make it work either.

Besides that, is is not logic to make a bundel a digitalproduct,
since there'e is no file for the bundel itself,  there are digitalproducts with there own files inside.

**Comment by muzzwood** [comment]
Related to https://github.com/modmore/docs/issues/242
Closing.

**Comment by hurby** [comment]
Hi, is it possible to add a combination of a normal product and a digital product to a bundel and make delivery work?

Download links will only appear when bundel delivery type is set to digitalproduct. links will not appear when set to normal  delivery.

**Comment by muzzwood** [comment]
Ah looks like I forgot to mention needing to set it to digital product delivery type in the docs. I'll fix that.

Hmmm having different shipment types in the same bundle would be a challenge as I believe bundles weren't meant to work that way. Could you add this as an issue on the Digital Product repo? https://github.com/modmore/Commerce_DigitalProduct

We'll have to look into what we can do.

**Comment by hurby** [comment]
I think it works okay but only when adding only digital products to the bundle
Another problem arrised just now while testing.

Single digital downloads are appearing on the invoice , bundels are not.
Any ideas on this?

**Comment by hurby** [comment]
It was clear that that was needed,
So no probs there.

I wild like it to be independent of that status, rather just render the links in mail and pdf and take it as a normal transport product.

I,ve noticed another problem, I made one 


Met vriendelijke groet
Herbert Kroon
 





DBB
Website              https://www.dbb.nl 

 Disclaimer   
De informatie verzonden met dit e-mail bericht is vertrouwelijk en uitsluitend bestemd voor de 
 geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. 
 Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan. Indien u dit bericht foutief ontvangen hebt, wordt u gevraagd dit aan  afzender te melden en dit bericht te vernietigen.
 
 The information contained in this electronic mail message is privileged and confidential, and is  intended only for use of the addressee. If you are not the intended recipient, you are hereby notified that any disclosure, reproduction, distribution or other use of this communication is strictly prohibited. If you have received this communication in error, please notify the sender.

> Op 5 okt. 2023, om 12:43 heeft Murray Wood ***@***.***> het volgende geschreven:
> 
> Ah looks like I forgot to mention needing to set it to digital product delivery type in the docs. I'll fix that.
