### ISSUE TITLE
Redactor

### ISSUE THREAD

**Issue by matthewwhalley** [modmore/docs#31]
On page [Redactor](https://github.com/modmore/docs/blob/master/en/04_Redactor/01_v2.x/index.md) there is an issue with ...

Feature request: When adding a link would it be possible to be able to select whether it is dofollow or nofollow?

**Comment by Mark-H** [comment]
Hi @matthewwhalley - if you still need help with that (I don't know the answer from the top of my head) please contact support. Issues in this repository are meant for documentation bugs :)
