### ISSUE TITLE
Auto-linked Headers with ContentBlocks

### ISSUE THREAD

**Issue by juro** [modmore/docs#32]
On page [Auto-linked Headers with ContentBlocks](https://github.com/modmore/docs/blob/master/en/02_ContentBlocks/v1.x/Tips_Tricks/00_Auto_Linked_Headers.md) there is an issue with ...
Very nice trick.
Althought IDs in HTML5 can be nearly everything, it might be not enought to replace spaces. Periods, colons and hash symbols have special meaning in CSS selectors and can ruin functionality of dynamic components. I would suggest someting like this, leaving only letters and numbers as unique ID:
id="jump_[[+value:md5:limit=`15`]]"
For repeater we add idx placeholder in case there are two equal items:
id="jump_[[+value:md5:limit=`15`]]_[[+idx]]"
In subcomponents like repeater and sublayout it would be great to have access to current level and parent idx, or some global unique idx. Some UI components are heavily dependent on globally unique element ID.

**Comment by Mark-H** [comment]
There's `[[+layout_idx]]`, `[[+field_idx]]` (or just `[[+idx]]`) and a `[[+unique_idx]]` placeholder available in most places :)

The benefit of using the value directly is that the link makes sense, while md5 would also do the trick and indeed be safer, it's just random gibberish to the user/visitor. 

The best way to handle it is to add a field setting to your headers where you can enter the id manually, but not all clients can be trusted to consistently do that ;)
