### ISSUE TITLE
Grabbing the First Image

### ISSUE THREAD

**Issue by Jako** [modmore/docs#35]
On page [Grabbing the First Image](https://github.com/modmore/docs/blob/master/en/02_ContentBlocks/v1.x/Tips_Tricks/03_Grabbing_the_First_Image.md) there is an issue with ...

firstImageTpl chunk has the wrong content

**Comment by Mark-H** [comment]
This was fixed in https://github.com/modmore/docs/commit/a12b4adf940381026c3831ca30b36a52e74fe3b7 - someone emailed me about the same which I saw sooner, sorry :P
