### ISSUE TITLE
Grabbing the First Image

### ISSUE THREAD

**Issue by Jako** [modmore/docs#36]
On page [Grabbing the First Image](https://github.com/modmore/docs/blob/master/en/02_ContentBlocks/v1.x/Tips_Tricks/03_Grabbing_the_First_Image.md) there is an issue with the placeholder: It should contain `url` instead of `value`. I also made a pthumb addition.

Create a chunk called firstImageTpl. As we just want the image url, the chunk is super simple:

```
[[+url]]
```

If you have pThumb installed, you could crop that image with:

```
[[+url:pthumb=`w=1200&h=1200&zc=1`]]
```

**Comment by Mark-H** [comment]
Added some notes and fixed the placeholder, thanks :)
