### ISSUE TITLE
Trigger Extract

### ISSUE THREAD

**Issue by Spheerys** [modmore/docs#77]
On page [Trigger Extract](https://github.com/modmore/docs/blob/master/en/50_Open_Source/GitifyWatch/05_Trigger_Extract.md) there is an issue with the domain name.
You are saying : 

> If it's not triggering, **it might not be recognising the domain name**, or your .gitify file. In most cases you will see more information about such errors in the MODX error log, though in rare circumstances errors will also be logged to your PHP error log.
> 
> When the extract task is triggered, it can sometimes fail to recognise the environment because it doesn't know the domain name. **In that case, double check if your core/config/config.inc.php file contains the right hostname**.

But in my config.inc.php file, I don't have any lines about my domain name : just variables about my database connection, and other stuff, but nothing about my domain.

**Comment by Mark-H** [comment]
Sorry @Spheerys, missed the notification. The relevant portion in the config file is around line 60 where it sets the `$http_host` variable:

```php

if (!defined('MODX_HTTP_HOST')) {
    if(defined('PHP_SAPI') && (PHP_SAPI == "cli" || PHP_SAPI == "embed")) {
        $http_host='localhost';
        define('MODX_HTTP_HOST', $http_host);
    } else {
    ...
}
```
